server:
   port: 8081
   servlet:
      context-path: /online

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;sslProtocol=TLS;databaseName=MyDB
    username: sa 
    password: 25262728
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  security:
    user:
      name: admin
      password: 12345
  thymeleaf:
      cache: false    

#springdoc:
#  api-docs.enabled: false
#  swagger-ui.enabled: false

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug   
        type:
          descriptor:
            sql:
              BasicBinder: trace                  
  
